In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [10]:
df = pd.read_csv('Tennis_dataset.csv')
# before = pd.read_csv('Tennis_dataset.csv')
df

     Outlook Temperature Humidity  Windy PlayTennis
0      Sunny         Hot     High  False         No
1      Sunny         Hot     High   True         No
2   Overcast         Hot     High  False        Yes
3      Rainy        Mild     High  False        Yes
4      Rainy        Cool   Normal  False        Yes
5      Rainy        Cool   Normal   True         No
6   Overcast        Cool   Normal   True        Yes
7      Sunny        Mild     High  False         No
8      Sunny        Cool   Normal  False        Yes
9      Rainy        Mild   Normal  False        Yes
10     Sunny        Mild   Normal   True        Yes
11  Overcast        Mild     High   True        Yes
12  Overcast         Hot   Normal  False        Yes
13     Rainy        Mild     High   True         No

In [11]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

order_map = [['Overcast', 'Rainy', 'Sunny']]
order_map1 = [['Mild', 'Cool', 'Hot']]
order_map2 = [['Normal', 'High']]


encoder = OrdinalEncoder(categories=order_map)
encoded_df = encoder.fit_transform(df[['Outlook']])
df['Outlook'] = encoded_df

encoder1 = OrdinalEncoder(categories=order_map1)
encoded_df1 = encoder1.fit_transform(df[['Temperature']])
df['Temperature'] = encoded_df1

encoder2 = OrdinalEncoder(categories=order_map2)
encoded_df2 = encoder2.fit_transform(df[['Humidity']])
df['Humidity'] = encoded_df2

encoder3 = LabelEncoder()
encoded_df3 = encoder3.fit_transform(df['Windy'])
df['Windy'] = encoded_df3

df.head()

   Outlook  Temperature  Humidity  Windy PlayTennis
0      2.0          2.0       1.0      0         No
1      2.0          2.0       1.0      1         No
2      0.0          2.0       1.0      0        Yes
3      1.0          0.0       1.0      0        Yes
4      1.0          1.0       0.0      0        Yes

In [16]:
from sklearn.tree import DecisionTreeClassifier

X = df.drop('PlayTennis', axis=1)
y = df['PlayTennis']

dtree = DecisionTreeClassifier()
dtree.fit(X, y)
pred = dtree.predict([[2.0, 2.0, 1.0, 1]])
pred

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)